name: travelpals
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  intl: ^0.17.0
  pin_code_fields: ^7.4.0
  flutter_multi_select_items: ^0.4.2
  flutter_screenutil: ^5.5.4
  carousel_indicator: ^1.0.6
  get_storage: ^2.0.3
  image_picker: ^0.8.6
  video_player: ^2.4.7
  flutter_contacts: ^1.1.5
  url_launcher: ^6.1.6
  swipeable_card_stack: ^0.0.5
  validator:
    path: 'packages/validator'
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
      - images/
      - json/

  fonts:
    - family: Schyler
      fonts:
      - asset: fonts/MuseoSans-Regular.otf
      - asset: fonts/MuseoSans-Regular-300.otf
      - asset: fonts/MuseoSans-SemiBold.otf
      - asset: fonts/MuseoSans-Bold.otf
      - asset: fonts/AmsiProNarw-Regular.otf
      - asset: fonts/AmsiProNarw-SemiBold.otf
